const path = require('path');
const fs = require('fs');

// Creates a config file to send to the PrusaSlicer based on the parameters selected in the front.
const generateConfig = (quality, supports) => {
  const configPath = path.resolve('uploads/config.ini'); // Path to save the config file

  // Map quality to PrusaSlicer settings
  const qualitySettings = {
    low: '0.3', // 0.3 mm layer height for low quality
    medium: '0.2', // 0.2 mm layer height for medium quality
    high: '0.1', // 0.1 mm layer height for high quality
  };

  // Check for valid quality
  if (!qualitySettings[quality]) {
    throw new Error('Invalid quality setting. Choose low, medium, or high.');
  }

  // Generate the content of the config file
  const configContent = `# Generated by 3D Print Price Calculator
layer_height = ${qualitySettings[quality]}
support_material = ${supports === 'yes' ? 1 : 0}
`;

  // Write the config file
  fs.writeFileSync(configPath, configContent, 'utf8');
  console.log('Configuration file generated at:', configPath);

  return configPath; // Return the path to the config file
};

module.exports = { generateConfig };
